spring.application.name=mini-zhipin-app

# 解决中文乱码问题
spring.banner.charset=UTF-8
spring.messages.encoding=UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# 日志编码配置
logging.charset.console=UTF-8
logging.charset.file=UTF-8

# JVM 编码配置（通过系统属性传递）
file.encoding=UTF-8
sun.jnu.encoding=UTF-8

server.port=8888
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=10,expireAfterWrite=6h

spring.mail.host=smtp.126.com
spring.mail.port=465
spring.mail.username=zhipin_mini_app@126.com
spring.mail.password=LDtTD7XRcKzRm7Zv
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.default-encoding=UTF-8

#logging.level.org.springframework.web.client.RestTemplate=DEBUG