spring.application.name=mini-zhipin-app

server.port=8888
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=10,expireAfterWrite=8h

spring.mail.host=smtp.126.com
spring.mail.port=465
spring.mail.username=zhipin_mini_app@126.com
spring.mail.password=LDtTD7XRcKzRm7Zv
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.default-encoding=UTF-8

#logging.level.org.springframework.web.client.RestTemplate=DEBUG
